Index.html, assets/js/script.js
Merge 'feature/add-initial-files' into main
=> Added initial files

assets/js/script.js
Merge 'feature/read-from-api-ninja' into main
=> Read data from api Ninja

assets/js/script.js, index2.html
Merge 'feature/search-and-filtering' into main
=> Added search and filtering

assets/js/catalogue.js, catalogue.html
Merge 'feature/add-catalogue-in-back-end' into main
=> Add catalogue in backend - now updates dynamic html

assets/js/api-thecat.js
added a function to get a random cat image via api. as well as a function that inserts an image in HTML into the img tag by id - main-image
=> added a function to get a random cat image via api

assets/js/api-thecat.js
the url for the function to get a random cat image was specified incorrectly
=> correction

assets/js/catalogue.js
added a function to add stars to cats. a constant was created with the location of the star image
=> added a function.  a constant was created

assets/js/helperLocalStorage.js
a helperLocalStorage.js file has been created to save and load data from/to the search page and local storage
=> a helperLocalStorage.js file has been created 

assets/js/script.js
Merge 'feature/update-script-js-to-display-cat-photos' into main
=> Script.js updated to display photos on search.html page

assets/js/script.js
Merge 'feature/add-cat-info-to-search-results' into main
=> Information on cat added

assets/js/script.js
Merge 'feature/add-origin-of-cat' into main
=> Added origin of cat in Catalogue and Search pages

search.html
Merge 'feature/fix-max-weight-issue' into main
=> Max weight in search.html was referred to as Min Weight!

assets/js/api-ninja.js, assets/js/helperLocalStorage.js, assets/js/script.js, assets/js/searchCat.js, search.html
Merge 'add-local-storage-functionality' into main
=> Added local storage functionality both loading and saving

assets/css/search_style.css, search.html
Merge 'feature/searchform-changes' into main
=> added max weight, spaceholder, min values, searchbox frame

assets/js/api-thecat.js
the logic for getting and using a random cat has been reworked. 
two functions to get a random cat using the api. 
show a random cat. 
binding to a button displaying a random cat
=> the logic for getting and using a random cat has been reworked.

assets/js/script.js, search.html
Merge 'feature/DynamicCardsCreation' into main
=> Dynamic creation of cards in both search.html and catalogue.html

assets/js/script.js
Merge 'feature/add-further-details-on-card' into main
=> Add min and max weight plus min and max life expectancy on all cards

assets/js/searchCat.js
=> Fixed clear search button for search page

assets/js/searchCat.js, search.html
added a line to clear search results and added a script to the html page to display a random cat
=> added a line to clear search results and added a script to the html page to display a random cat

assets/js/searchCat.js
Merge 'feature/cat-breed-name-not-loading-search-form' into main
=> Cat breed name now loading in search form

assets/js/searchCat.js
Merge 'feature/fix-search-filtering' into main
=> Fixed bug in Search Filtering

assets/js/script.js
Merge 'feature/fix-search-results-title' into main
=> Fixed search results title so grammar made sense

README.md
Merge 'feature/update-readme-file-first-draft' into main
=> Update Readme file (first draft)

README.md
Merge 'feature/update-ninja-api-link' into main
=> Updated ninja api website link in readme file

assets/js/script.js, assets/js/searchCat.js, search.html
Merge 'feature/add-sorting-to-search-page' into main
=> Sorting has been implemented on 'search.html'

assets/js/catalogue.js, assets/js/script.js, assets/js/searchCat.js
Merge 'feature/move-js-code-from-search-to-catalogue-page' into main
=> Code for sorting moved from search to catalogue form

assets/js/catalogue.js, assets/js/script.js
Merge 'feature/fix-catalogue-so-it-loads-cats-on-startup' into main
=> Fix catalogue so when web page loads, all cats are displayed

assets/js/api-thecat.js
added error output to modal window
=> added error output to modal window
